name: CDPipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /home/ubuntu/fastapi-app

            # Pull latest changes
            git pull origin main

            # Set up Python virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the FastAPI application
            sudo systemctl restart fastapi-book-project
